export const GET_MOVIE_INFO_PENDING =
  "MOVIE_INFO::GET_MOVIE_INFO_PENDING";
export const GET_MOVIE_INFO_FULFILLED =
  "MOVIE_INFO::GET_MOVIE_INFO_FULFILLED";
export const GET_MOVIE_INFO_REJECTED =
  "MOVIE_INFO::GET_MOVIE_INFO_REJECTED";

export const GET_MOVIE_INFO_TRIGGER =
  "MOVIE_INFO::GET_MOVIE_INFO_TRIGGER";
