export const GET_MOVIES_PENDING = "MOVIES::GET_MOVIES_PENDING";
export const GET_MOVIES_FULFILLED = "MOVIES::GET_MOVIES_FULFILLED";
export const GET_MOVIES_REJECTED = "MOVIES::GET_MOVIES_REJECTED";

export const GET_MOVIES_TRIGGER = "MOVIES::GET_MOVIES_TRIGGER";
